In [46]:
import pandas as pd
import sklearn

In [47]:
df = pd.read_pickle('./f1_23_monaco.pkl')
df

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,...,TyreLife,FreshTyre,Team,LapStartTime,LapStartDate,TrackStatus,Position,Deleted,DeletedReason,IsAccurate
0,0 days 01:04:46.825000,VER,1,79.367,2,1,NaT,NaT,0 days 00:00:20.954000,0 days 00:00:37.366000,...,2,True,Red Bull Racing,0 days 01:03:27.458000,2023-05-28 13:04:28.435,1,1,False,NaN,True
1,0 days 01:04:48.393000,ALO,14,79.646,2,1,NaT,NaT,0 days 00:00:20.871000,0 days 00:00:37.656000,...,3,False,Aston Martin,0 days 01:03:28.747000,2023-05-28 13:04:29.724,1,2,False,NaN,True
2,0 days 01:04:50.160000,OCO,31,80.301,2,1,NaT,NaT,0 days 00:00:21.245000,0 days 00:00:37.737000,...,2,True,Alpine,0 days 01:03:29.859000,2023-05-28 13:04:30.836,1,3,False,NaN,True
3,0 days 01:04:51.203000,SAI,55,80.593,2,1,NaT,NaT,0 days 00:00:21.218000,0 days 00:00:37.827000,...,2,True,Ferrari,0 days 01:03:30.610000,2023-05-28 13:04:31.587,1,4,False,NaN,True
4,0 days 01:04:52.332000,HAM,44,80.527,2,1,NaT,NaT,0 days 00:00:21.226000,0 days 00:00:37.769000,...,2,True,Mercedes,0 days 01:03:31.805000,2023-05-28 13:04:32.782,1,5,False,NaN,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1254,0 days 02:51:57.562000,GAS,10,86.578,78,3,NaT,NaT,0 days 00:00:22.610000,0 days 00:00:41.552000,...,24,True,Alpine,0 days 02:50:30.984000,2023-05-28 14:51:31.961,1,7,False,NaN,True
1255,0 days 02:51:58.591000,SAI,55,86.283,78,3,NaT,NaT,0 days 00:00:22.537000,0 days 00:00:41.195000,...,23,True,Ferrari,0 days 02:50:32.308000,2023-05-28 14:51:33.285,1,8,False,NaN,True
1256,0 days 02:52:07.052000,ZHO,24,86.615,77,3,NaT,NaT,0 days 00:00:22.670000,0 days 00:00:41.227000,...,25,True,Alfa Romeo,0 days 02:50:40.437000,2023-05-28 14:51:41.414,1,13,False,NaN,True
1257,0 days 02:52:08.183000,SAR,2,89.076,76,4,NaT,NaT,0 days 00:00:24.523000,0 days 00:00:41.980000,...,24,True,Williams,0 days 02:50:39.107000,2023-05-28 14:51:40.084,1,18,False,NaN,True
1258,0 days 02:52:14.410000,ALB,23,87.816,77,3,NaT,NaT,0 days 00:00:23.207000,0 days 00:00:41.296000,...,25,True,Williams,0 days 02:50:46.594000,2023-05-28 14:51:47.571,1,14,False,NaN,True

In [ ]:
data_aston = df.loc[df['Team'] == "Aston Martin"]
data_aston.loc[:, ['Class']] = 0 
data_aston.loc[data_aston['Driver'] == "ALO",['Class']] = 1
data_aston.loc[data_aston['Driver'] != "ALO",['Driver', 'Class']]

    Driver  Class
16     STR      0
33     STR      0
53     STR      0
73     STR      0
93     STR      0
113    STR      0
133    STR      0
153    STR      0
173    STR      0
202    STR      0
221    STR      0
241    STR      0
260    STR      0
279    STR      0
298    STR      0
317    STR      0
336    STR      0
355    STR      0
375    STR      0
394    STR      0
413    STR      0
433    STR      0
453    STR      0
473    STR      0
493    STR      0
513    STR      0
534    STR      0
552    STR      0
569    STR      0
588    STR      0
608    STR      0
627    STR      0
647    STR      0
667    STR      0
687    STR      0
707    STR      0
727    STR      0
747    STR      0
767    STR      0
786    STR      0
805    STR      0
825    STR      0
844    STR      0
863    STR      0
883    STR      0
902    STR      0
954    STR      0

In [56]:
data_aston['Sector1Time'] = data_aston['Sector1Time'].dt.total_seconds()
data_aston['Sector2Time'] = data_aston['Sector2Time'].dt.total_seconds()
data_aston['Sector3Time'] = data_aston['Sector3Time'].dt.total_seconds()
data_aston['Class'] = (data_aston['Driver'] == 'ALO').astype(int)

AttributeError: Can only use .dt accessor with datetimelike values

In [50]:
X = data_aston.drop(columns='Class')
Y = data_aston['Class']

In [51]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [52]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.20, random_state=2533)

In [53]:
scaler = StandardScaler()

X_std     = scaler.fit_transform(X_train)  # fit + scale
X_test_std = scaler.transform(X_test)      # scale only!

DTypePromotionError: The DType <class 'numpy.dtypes.Float64DType'> could not be promoted by <class 'numpy.dtypes.TimeDelta64DType'>. This means that no common DType exists for the given inputs. For example they cannot be stored in a single array unless the dtype is `object`. The full list of DTypes is: (<class 'numpy.dtypes.TimeDelta64DType'>, <class 'numpy.dtypes.ObjectDType'>, <class 'numpy.dtypes.Int64DType'>, <class 'numpy.dtypes.Float64DType'>, <class 'numpy.dtypes.Int64DType'>, <class 'numpy.dtypes.Int64DType'>, <class 'numpy.dtypes.TimeDelta64DType'>, <class 'numpy.dtypes.TimeDelta64DType'>, <class 'numpy.dtypes.Float64DType'>, <class 'numpy.dtypes.Float64DType'>, <class 'numpy.dtypes.Float64DType'>, <class 'numpy.dtypes.Float64DType'>, <class 'numpy.dtypes.Float64DType'>, <class 'numpy.dtypes.Float64DType'>, <class 'numpy.dtypes.Float64DType'>, <class 'numpy.dtypes.BoolDType'>, <class 'numpy.dtypes.ObjectDType'>, <class 'numpy.dtypes.Int64DType'>, <class 'numpy.dtypes.BoolDType'>, <class 'numpy.dtypes.ObjectDType'>, <class 'numpy.dtypes.TimeDelta64DType'>, <class 'numpy.dtypes.DateTime64DType'>, <class 'numpy.dtypes.Int64DType'>, <class 'numpy.dtypes.Int64DType'>, <class 'numpy.dtypes.BoolDType'>, <class 'numpy.dtypes.ObjectDType'>, <class 'numpy.dtypes.BoolDType'>)